spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservice-config-client-dev
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
  instance:
    instance-id: microservice-config-client-dev
    prefer-ip-address: true
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservice-config-client-test
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
  instance:
    instance-id: microservice-config-client-test
    prefer-ip-address: true
